import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { GeneratedPaper, Question } from '@veda-ai/types';
import logger from '../utils/logger';

const PDF_DIR = process.env.PDF_OUTPUT_DIR || './pdfs';

// Ensure PDF directory exists
function ensurePdfDir(): void {
  if (!fs.existsSync(PDF_DIR)) {
    fs.mkdirSync(PDF_DIR, { recursive: true });
  }
}

// ─── Color helpers ────────────────────────────────────────────────────────────
function getDifficultyColor(difficulty: string): string {
  switch (difficulty) {
    case 'easy':   return '#16a34a'; // green
    case 'medium': return '#d97706'; // amber
    case 'hard':   return '#dc2626'; // red
    default:       return '#6b7280';
  }
}

// ─── PDF Generator ────────────────────────────────────────────────────────────
export async function generatePDF(
  paper: GeneratedPaper,
  assignmentId: string
): Promise<string> {
  ensurePdfDir();

  const fileName = `paper-${assignmentId}-${Date.now()}.pdf`;
  const filePath = path.join(PDF_DIR, fileName);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 70, right: 70 },
      info: {
        Title: paper.title,
        Author: 'Veda AI Assessment Creator',
      },
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // ── Header ──────────────────────────────────────────────────────────────
    doc
      .font('Helvetica-Bold')
      .fontSize(20)
      .fillColor('#1e293b')
      .text(paper.title, { align: 'center' });

    doc.moveDown(0.3);
    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor('#64748b')
      .text(`Generated by Veda AI  •  ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}`, { align: 'center' });

    // ── Divider ──────────────────────────────────────────────────────────────
    doc.moveDown(0.8);
    doc.moveTo(70, doc.y).lineTo(525, doc.y).strokeColor('#e2e8f0').lineWidth(1).stroke();
    doc.moveDown(0.8);

    // ── Student Info Box ─────────────────────────────────────────────────────
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#1e293b').text('Student Information', 70);
    doc.moveDown(0.4);

    const infoFields = [
      ['Name', '_'.repeat(40)],
      ['Roll Number', '_'.repeat(30)],
      ['Section', '_'.repeat(20)],
      ['Date', '_'.repeat(25)],
    ];

    infoFields.forEach(([label, blank]) => {
      doc
        .font('Helvetica-Bold').fontSize(10).fillColor('#374151')
        .text(`${label}: `, { continued: true })
        .font('Helvetica').fillColor('#1e293b')
        .text(blank);
      doc.moveDown(0.3);
    });

    // ── Divider ──────────────────────────────────────────────────────────────
    doc.moveDown(0.5);
    doc.moveTo(70, doc.y).lineTo(525, doc.y).strokeColor('#e2e8f0').lineWidth(1).stroke();
    doc.moveDown(0.8);

    // ── Sections ─────────────────────────────────────────────────────────────
    paper.sections.forEach((section, sIdx) => {
      // Section header
      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor('#1e293b')
        .text(section.title);

      doc.moveDown(0.2);
      doc
        .font('Helvetica-Oblique')
        .fontSize(10)
        .fillColor('#64748b')
        .text(section.instruction);
      doc.moveDown(0.6);

      // Questions
      section.questions.forEach((q: Question) => {
        // Check page space
        if (doc.y > 720) doc.addPage();

        // Question number + text
        doc
          .font('Helvetica-Bold')
          .fontSize(11)
          .fillColor('#1e293b')
          .text(`Q${q.questionNumber}. `, { continued: true })
          .font('Helvetica')
          .text(q.text);

        doc.moveDown(0.2);

        // Badges row: difficulty + marks + type
        const badgeY = doc.y;
        doc
          .font('Helvetica-Bold')
          .fontSize(9)
          .fillColor(getDifficultyColor(q.difficulty))
          .text(`[${q.difficulty.toUpperCase()}]`, { continued: true })
          .fillColor('#6b7280')
          .text(`  •  ${q.marks} mark${q.marks !== 1 ? 's' : ''}  •  ${q.type}`);

        // MCQ Options
        if (q.type === 'mcq' && q.options && q.options.length > 0) {
          doc.moveDown(0.3);
          q.options.forEach((opt) => {
            doc
              .font('Helvetica')
              .fontSize(10)
              .fillColor('#374151')
              .text(`    ${opt.label}. ${opt.text}`);
            doc.moveDown(0.15);
          });
        }

        // Answer space for non-MCQ
        if (q.type === 'short-answer') {
          doc.moveDown(0.3);
          doc.font('Helvetica').fontSize(9).fillColor('#94a3b8').text('Answer: _'.padEnd(80, '_'));
          doc.moveDown(0.2);
          doc.font('Helvetica').fontSize(9).fillColor('#94a3b8').text('_'.repeat(80));
        } else if (q.type === 'long-answer') {
          doc.moveDown(0.3);
          for (let i = 0; i < 5; i++) {
            doc.font('Helvetica').fontSize(9).fillColor('#94a3b8').text('_'.repeat(80));
            doc.moveDown(0.2);
          }
        }

        doc.moveDown(0.6);
      });

      // Section separator
      if (sIdx < paper.sections.length - 1) {
        doc.moveDown(0.3);
        doc.moveTo(70, doc.y).lineTo(525, doc.y).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
        doc.moveDown(0.8);
      }
    });

    // ── Footer ───────────────────────────────────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#94a3b8')
        .text(`Page ${i + 1} of ${range.count}  |  Veda AI`, 70, 780, {
          align: 'center',
          width: 455,
        });
    }

    doc.end();

    stream.on('finish', () => {
      logger.info(`PDF generated: ${filePath}`);
      resolve(`/pdfs/${fileName}`);
    });
    stream.on('error', reject);
  });
}
